/**
 * This file is automatically generated. It is not meant for manual editing.
 * Generated: 6:59 PM Friday, June 19, 2026
 */

#Import "C:\Programming\ahklint\lints\ffi\UseTypedCallbacks.ahk" { UseTypedCallbacks }
#Import "C:\Programming\ahklint\lints\misc\NoGotos.ahk" { NoGotos }
#Import "C:\Programming\ahklint\lints\misc\OneRequires.ahk" { OneRequires }
export global ALL_LINTS := [
    UseTypedCallbacks,
    NoGotos,
    OneRequires,
]
