/**
 * This file is automatically generated. It is not meant for manual editing.
 * Generated: 5:24 PM Wednesday, June 17, 2026
 */

#Import "C:\Programming\ahklint\lints\misc\NoGotos.ahk" { NoGotos }
export global ALL_LINTS := [
    NoGotos,
]
