/**
 * This file is automatically generated. It is not meant for manual editing.
 * Generated: 8:51 PM Wednesday, June 17, 2026
 */

#Import "C:\Programming\ahklint\lints\misc\NoGotos.ahk" { NoGotos }
#Import "C:\Programming\ahklint\lints\misc\OneRequires.ahk" { OneRequires }
export global ALL_LINTS := [
    NoGotos,
    OneRequires,
]
